name: Build, Test and Package

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Добавляем явные права на запись
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
        
    - name: Configure and Build
      run: |
        mkdir -p build
        cd build
        cmake -DINSTALL_GTEST=OFF ..
        make -j$(nproc)
        
    - name: Run tests
      run: |
        cd build
        ./computer_tests
        
    - name: Create DEB package
      run: |
        cd build
        cpack
        ls -lh *.deb  # Показываем созданный пакет
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: build/*.deb
        
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/*.deb"
        generateReleaseNotes: true
        tag: "v$(date +%Y%m%d%H%M%S)"
        name: "Release $(date +'%Y-%m-%d %H:%M:%S')"
        token: ${{ secrets.GITHUB_TOKEN }}
