name: Build, Test and Package

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set version
      id: set-version
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        SHORT_SHA=$(git rev-parse --short HEAD)
        # Генерируем версию в формате, совместимом с Debian
        VERSION="1.0.${TIMESTAMP}.${SHORT_SHA}"
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "Generated version: ${VERSION}"
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
        
    - name: Configure and Build
      run: |
        mkdir -p build
        cd build
        # Передаем версию в CMake
        cmake -DINSTALL_GTEST=OFF -DPACKAGE_VERSION="${{ steps.set-version.outputs.version }}" ..
        make -j$(nproc)
        
    - name: Run tests
      run: |
        cd build
        ./computer_tests
        
    - name: Create DEB package
      run: |
        cd build
        cpack
        ls -lh *.deb
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: build/*.deb
        
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ steps.set-version.outputs.version }}"
        name: "Release v${{ steps.set-version.outputs.version }}"
        files: build/*.deb
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
