name: Build, Test and Package

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set version
      id: set-version
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        SHORT_SHA=$(git rev-parse --short HEAD)
        echo "version=v1.0.${TIMESTAMP}-${SHORT_SHA}" | tee version.txt
        echo "version=${version}" >> $GITHUB_OUTPUT
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
        
    - name: Configure and Build
      run: |
        mkdir -p build
        cd build
        cmake -DINSTALL_GTEST=OFF ..
        make -j$(nproc)
        
    - name: Run tests
      run: |
        cd build
        ./computer_tests
        
    - name: Create DEB package
      run: |
        cd build
        # Используем версию из шага set-version
        sed -i "s/set(CPACK_PACKAGE_VERSION \"1.0.0\")/set(CPACK_PACKAGE_VERSION \"${{ steps.set-version.outputs.version }}\")/" ../CMakeLists.txt
        cmake --build . --target package
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: build/*.deb
        
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.set-version.outputs.version }}
        name: "Release ${{ steps.set-version.outputs.version }}"
        files: build/*.deb
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
