name: Build, Test and Package

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
        
    - name: Configure and Build
      run: |
        mkdir -p build
        cd build
        cmake -DINSTALL_GTEST=OFF ..
        make -j$(nproc)
        
    - name: Run tests
      run: |
        cd build
        ./computer_tests
        
    - name: Create DEB package
      run: |
        cd build
        cpack
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: build/*.deb
        
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v$(date +%Y%m%d%H%M%S)"
        name: "Release $(date +'%Y-%m-%d %H:%M:%S')"
        files: build/*.deb
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
